apiVersion: v1
kind: Namespace
metadata:
  name: dkramich

---
 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-wc
  namespace: dkramich
  labels:
    app: helloworld-wc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-wc
  template:
    metadata:
      labels:
        app: helloworld-wc
    spec:
      containers:
      - image: docker.k8s.dkramich.playpit.by/helloworld-dkramich:"${BUILD_NUMBER}"
        name: webapp
        ports: 
          - containerPort: 8080
            name: helloworld-port
        imagePullPolicy: Always
        
        livenessProbe:
          exec:
            command:
            - bash
            - /tmp/check.sh
          initialDelaySeconds: 10
          periodSeconds: 5

        readinessProbe:
          httpGet:
            path: /helloworld-ws
            port: helloworld-port
          initialDelaySeconds: 10
          periodSeconds: 5
      imagePullSecrets:
      - name: myregistry

---

apiVersion: v1
kind: Service
metadata:
  name: helloworld-wc-service
  namespace: dkramich
spec:
  selector:
    app: helloworld-wc
  ports:
  - protocol: TCP
    name: helloworld-port
    port: 80
    targetPort: 8080

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: helloworld-wc
  namespace: dkramich
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: dkramich.k8s.dkramich.playpit.by
      http:
        paths:
        - path: /
          backend:
            serviceName: helloworld-wc-service
            servicePort: 80

